services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080" # Web interface
      - "1026:1025" # SMTP server

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mailcatcher
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432
      SECRET_KEY_BASE: 123456789abcdef
      MAILER_URL: smtp://mailcatcher:1025
    tty: true

volumes:
  pgdata:
